# Generated by Django 4.0 on 2021-12-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Title', max_length=50, verbose_name='Title')),
                ('Subtitle', models.CharField(default='Subtitle', max_length=50, verbose_name='Subtitle')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
